name: Android CI with Security Scan

on:
  workflow_dispatch:
    inputs:
      google_maps_api_key:
        description: 'Google Maps API Key'
        required: true
        type: string

  schedule:
    - cron: '0 2 * * *'

jobs:
  build-and-test:
    name: Build & Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Create apikeys.properties
        run: |
          echo "GOOGLE_MAPS_API_KEY=${{ inputs.google_maps_api_key }}" > ./apikeys.properties

      - name: Build project
        run: ./gradlew build -x lint

      - name: Run unit tests
        run: ./gradlew test

  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java
      
      - name: Create apikeys.properties
        run: |
          echo "GOOGLE_MAPS_API_KEY=${{ inputs.google_maps_api_key }}" > ./apikeys.properties

      - name: Build project
        run: ./gradlew build -x lint

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
